# Generated by Django 3.0.5 on 2020-04-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='null', upload_to='covers/'),
            preserve_default=False,
        ),
    ]
